backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artworks"
    label: "Œuvres"
    files:
      - file: "artworks.json"
        label: "Galerie"
        name: "galerie"
        fields:
          - label: "Œuvres"
            name: "oeuvres"
            widget: "list"
